baseURL = 'https://narnacle.github.io/lunar-hugo/'
languageCode = 'en-US'
title = 'LunaR'

theme = 'lunar-hugo'

[menus]
	[[menus.main]]
		name = 'about'
		pageRef = '/about'

	[[menus.main]]
		name = 'blog'
		pageRef = '/blog'

	[[menus.main]]
		name = 'website'
		url = 'https://narnacle.com'

[params]
	[params.author]
		email = 'example@example.com'
